services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
    external: true