name: start app

on:
  push:
    branches: [main, master]
env:
  IMAGE_NAME: service-registry
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/service-registry
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code check
        uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Create micro-net network
        run: |
          docker network create micro-net || true
      - name: Build with Gradle
        run: ./gradlew clean build
  build-and-push-image:
    name: Building Docker image
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Code check
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}